### PR TITLE
fix: resolver for environment openshift needs to do a project lookup

### LINKED ISSUE #2972: Permission issue resolving kubernetes for environments
# Describe the bug

When querying an environments kubernetes resolver, a permission denied is encountered if you are not an admin
```
projectByName(name: $name) {
  id
  name
  environments {
    id
    name
    environmentType
    openshiftProjectName
    kubernetes {
      id
    }
  }
}
```

## Expected behavior

It should resolve the same for querying the kubernetes at the project level.

### PR DESCRIPTION
**Pull request by shreddedbacon**
# Checklist

- [x] Affected Issues have been mentioned in the Closing issues section
- [ ] Documentation has been written/updated
- [ ] PR title is ready for changelog and subsystem label(s) applied

# Closing issues

closes #2972

### CODE REVIEW

File: services/api/src/resources/openshift/resolvers.ts [hunk 1]
```diff
@@ -114,7 +114,22 @@ export const getOpenshiftByEnvironmentId: ResolverFn = async (
   args,
   { sqlClientPool, hasPermission }
 ) => {
-  await hasPermission('openshift', 'viewAll');
+  // get the project id for the environment
+  const projectrows = await query(
+    sqlClientPool,
+    `SELECT e.project
```
Comment (rocketeerbkw) [inline services/api/src/resources/openshift/resolvers.ts]: There is a preference to reduce raw sql queries in resolvers. For permissions checks you could  re-use a knex/sql object `selectProjectByEnvironmentId` (first [import](https://github.com/uselagoon/lagoon/blob/main/services/api/src/resources/environment/resolvers.ts#L11), then use) or avoid the `query` all together by using a project helper like `getProjectByEnvironmentId` (first [import](https://github.com/uselagoon/lagoon/blob/main/services/api/src/resources/environment/resolvers.ts#L12), then [use](https://github.com/uselagoon/lagoon/blob/main/services/api/src/resources/environment/resolvers.ts#L244-L246))

**Review by rocketeerbkw — CHANGES_REQUESTED** [review]

File: services/api/src/resources/openshift/resolvers.ts (hunk 1 above)
Comment (shreddedbacon) [reply services/api/src/resources/openshift/resolvers.ts]: refactored with the helper

**Review by rocketeerbkw — APPROVED** [review]
