### PR TITLE
876 environment limit display

### LINKED ISSUE #876: Display the limit of environments
Current issues:
- Developers might not know about the limit of environments
- Currently there is no way to learn the limit (maybe via API? but still not so obvious)

Proposed solutions:
- Variant A: add the limit of environments to the Lagoon UI
- Variant B: add a (Slack) notification, like  
    > :warning: **[project]** PR [#123 (PR name)](#) opened in Company/project
    > ERROR: environment won't be created because the limit of environments is already reached.
- Variant C: A+B

### PR DESCRIPTION
**Pull request by rtprio**
# Checklist
- [x] Affected Issues have been mentioned in the Closing issues section
- [ ] Documentation has been written/updated.
- [x] Changelog entry has been written

Previously, there was no way to determine what the development environment limit was. This change will add it as a field to the UI.

# Changelog Entry
 
Improvement - Displays number of used and limit of non-production environments (#876 )

# Closing issues
Closes #876

### CODE REVIEW

**Comment by rtprio** [comment]
screen shot

File: services/ui/src/components/Project/index.js [hunk 1]
```diff
@@ -68,6 +72,12 @@ class Project extends React.Component {
               <div className='field'>{this.props.project.pullrequests}</div>
             </div>
           </div>
+          <div className='field-wrapper envlimit'>
+            <div>
+              <label>Non-Production environments in use</label>
+              <div className='field'>{this.state.developEnvironmentCount} of {this.props.project.developmentEnvironmentsLimit} </div>
```
Comment (rocketeerbkw) [inline services/ui/src/components/Project/index.js]: Is `developmentEnvironmentsLimit` always a number? It looks like it can be set to null to mean unlimited? Think it would be nice to display "x of unlimited" or "x of ∞" if that's the case.

Comment (rtprio) [reply services/ui/src/components/Project/index.js]: That's a good point.  New projects are created with a default (5), but it is nullable so that's something I should consider.

Comment (rtprio) [reply services/ui/src/components/Project/index.js]: I've updated this to safely tolerate null.

File: services/ui/src/components/Project/index.js [hunk 2]
```diff
@@ -68,6 +72,12 @@ class Project extends React.Component {
               <div className='field'>{this.props.project.pullrequests}</div>
             </div>
           </div>
+          <div className='field-wrapper envlimit'>
+            <div>
+              <label>Non-Production environments in use</label>
```
Comment (Schnitzel) [inline services/ui/src/components/Project/index.js]:
```suggestion
              <label>Development environments in use</label>
```

Let's call them what they are: `Development Environments`, I would like to not introduce a new word "non-production" when they are called "development" in the API.

**Review by Schnitzel — CHANGES_REQUESTED** [review]
