### PR TITLE
Check for the existence of private container registry password better

### LINKED ISSUE #2338: Private container registry incorrectly sets login password
When using the private container registry setup in Lagoon, if you define a password in the lagoon API at the project level, but you have environment level variables defined. The check used will prioritise the environment level variable first, but if there is one not defined, it will set it to an empty value.

https://github.com/amazeeio/lagoon/blob/f2fe153eab7da3c932f8b66b5c7136115a8c1bdc/images/oc-build-deploy-dind/build-deploy-docker-compose.sh#L263-L268

The logic needs to be updated to check if the value is not empty before setting it.

### PR DESCRIPTION
**Pull request by shreddedbacon**
# Checklist

- [x] Affected Issues have been mentioned in the Closing issues section
- [ ] Documentation has been written/updated
- [ ] PR title is ready for changelog and subsystem label(s) applied

In certain conditions, if an environment has a private container registry configured with credentials in the API at the project level, if any environment level variables are added then the private container registry credential would get set to an empty value and fail.

This checks that the credential is not empty before setting it, and also informs the user if no credential can be found.

# Closing issues

closes #2338

### CODE REVIEW

File: images/kubectl-build-deploy-dind/build-deploy.sh [hunk 1]
```diff
@@ -97,12 +97,19 @@ do
...
+      if [ ! -z "$TEMP_PRIVATE_REGISTRY_CREDENTIAL" ]; then
+        PRIVATE_REGISTRY_CREDENTIAL=$TEMP_PRIVATE_REGISTRY_CREDENTIAL
+      fi
     fi
     if [ -z $PRIVATE_REGISTRY_CREDENTIAL ]; then
       #if no password defined in the lagoon api, pass the one in `.lagoon.yml` as a password
       PRIVATE_REGISTRY_CREDENTIAL=$PRIVATE_CONTAINER_REGISTRY_PASSWORD
     fi
+    if [ ! -z "$PRIVATE_REGISTRY_CREDENTIAL" ]; then
+      echo -e "A private container registry wass defined on the .lagoon.yml file, but no password could be found in either the .lagoon.yml or in the Lagoon API\n\nPlease check if the password has been set correctly."
```
Comment (AlexSkrypnyk) [inline images/kubectl-build-deploy-dind/build-deploy.sh]:
```suggestion
      echo -e "A private container registry was defined in the .lagoon.yml file, but no password could be found in either the .lagoon.yml or in the Lagoon API\n\nPlease check if the password has been set correctly."
```

File: images/oc-build-deploy-dind/build-deploy-docker-compose.sh [hunk 2]
```diff
@@ -269,12 +269,19 @@ do
...
+      if [ ! -z "$TEMP_PRIVATE_REGISTRY_CREDENTIAL" ]; then
+        PRIVATE_REGISTRY_CREDENTIAL=$TEMP_PRIVATE_REGISTRY_CREDENTIAL
+      fi
     fi
     if [ -z $PRIVATE_REGISTRY_CREDENTIAL ]; then
       #if no password defined in the lagoon api, pass the one in `.lagoon.yml` as a password
       PRIVATE_REGISTRY_CREDENTIAL=$PRIVATE_CONTAINER_REGISTRY_PASSWORD
     fi
+    if [ ! -z "$PRIVATE_REGISTRY_CREDENTIAL" ]; then
+      echo -e "A private container registry wass defined on the .lagoon.yml file, but no password could be found in either the .lagoon.yml or in the Lagoon API\n\nPlease check if the password has been set correctly."
```
Comment (AlexSkrypnyk) [inline images/oc-build-deploy-dind/build-deploy-docker-compose.sh]:
```suggestion
      echo -e "A private container registry was defined in the .lagoon.yml file, but no password could be found in either the .lagoon.yml or in the Lagoon API\n\nPlease check if the password has been set correctly."
```

**Review by cdchris12 — APPROVED** [review]
Good eye! Looks good to me
