### PR TITLE
Harbor Robot Account Generation Fixup

### LINKED ISSUE #2342: Harbor Robot Account Created For Incorrect Project
# Describe the bug

When calling the Harbor API to obtain a project's harbor repository ID, Lagoon currently blindly takes the first result returned with no verification as to whether or not that is the correct project. This is an issue because the Harbor API returns a list of any projects whose names contain the string which was searched for.

The issue is here: https://github.com/amazeeio/lagoon/blob/main/services/api/src/resources/project/harborSetup.ts#L58

### PR DESCRIPTION
**Pull request by cdchris12**
# Checklist

- [X] Affected Issues have been mentioned in the Closing issues section
- [X] PR title is ready for changelog and subsystem label(s) applied

This PR adds pagination support and project name matching logic to substantially increase the functionality of the harbor robot account generation process.

# Closing issues

Closes #2342

### CODE REVIEW

File: services/api/src/resources/project/harborSetup.ts [hunk 1]
```diff
@@ -50,8 +50,31 @@ async function createHarborProject(sqlClient: MariaClient, harborClient, lagoonP
...
+    let results = []
+    let res = await harborClient.get(`projects?name=${lagoonProjectName}&page_size=${pageSize}`)
+
+    if (parseInt(res.headers['x-total-count']) > pageSize) {
+      let i = 1
+      while (res.body != null) {
+        results = results.concat(res.body)
+        i++
+        res = await harborClient.get(`projects?name=${lagoonProjectName}&page_size=${pageSize}&page=${i}`)
+        console.log(res.body)
```
Comment (rocketeerbkw) [inline services/api/src/resources/project/harborSetup.ts]: Was this overlooked? That's gonna add a lot of cruft to sift through if anyone needs to look at the API logs.

**Review by rocketeerbkw — CHANGES_REQUESTED** [review]

File: services/api/src/resources/project/harborSetup.ts (hunk 1 above)
Comment (cdchris12) [reply services/api/src/resources/project/harborSetup.ts]: Good catch; removed

**Review by rocketeerbkw — APPROVED** [review]
